version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ai-backend
    environment:
      - SCW_ACCESS_KEY=${SCW_ACCESS_KEY}
      - SCW_SECRET_KEY=${SCW_SECRET_KEY}
    networks:
      - app-network
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ai-frontend
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: ai-nginx
    ports:
      - "8080:8080"  # Port eşleştirmesini güncelledik
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - frontend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
